name: flutterguide
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.18.1
  flutter_animate: ^4.2.0+1
  flutter_gen: ^5.3.2
  get: ^4.6.6
  flutter_bloc: ^8.1.3
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  audioplayers: ^5.2.0
  responsive_framework: ^0.2.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_gen:
  output: lib/src/core/assets/