// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvHJARn1eNaupEIkvNA26YbaStsTEmaQk',
    appId: '1:243779894782:web:a68279b899b96f8ec9d4af',
    messagingSenderId: '243779894782',
    projectId: 'forex-b5fd7',
    authDomain: 'forex-b5fd7.firebaseapp.com',
    storageBucket: 'forex-b5fd7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh9h7qXM0PUoCjyprAu9oQRKYKV76KrTI',
    appId: '1:243779894782:android:501b3cdebb2c3323c9d4af',
    messagingSenderId: '243779894782',
    projectId: 'forex-b5fd7',
    storageBucket: 'forex-b5fd7.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvHJARn1eNaupEIkvNA26YbaStsTEmaQk',
    appId: '1:243779894782:web:13d2958f20959b91c9d4af',
    messagingSenderId: '243779894782',
    projectId: 'forex-b5fd7',
    authDomain: 'forex-b5fd7.firebaseapp.com',
    storageBucket: 'forex-b5fd7.appspot.com',
  );
}
